/**:
  ros__parameters:
    log_dir: /home/yuchen/ASRL/temp/doppler_odometry/boreas/aeva/spline

    # SLAM OPTIONS ----
    save_trajectory: true
    suspend_on_failure: false
    output_dir: /home/yuchen/ASRL/temp/doppler_odometry/boreas/aeva/spline

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: false
      raw_points: false
      sampled_points: false
      map_points: false
      T_sr_vec: [-0.835, -0.39, 0.103, 0.0, 0.0, 0.0] # davids result without side slip

    # DATASET OPTIONS ----
    dataset: AEVA # Options: [KITTI_raw / KITTI_CARLA / KITTI / KITTI-360 / BOREAS / AEVA]
    dataset_options:
      all_sequences: true
      root_path: /home/yuchen/ASRL/data/boreas/sequences
      sequence: "boreas-2022-05-13-10-30"
      min_dist_lidar_center: 5.0
      max_dist_lidar_center: 100.0

    # ODOMETRY OPTIONS ----
    odometry: SPLINE
    odometry_options:
      init_num_frames: 20
      voxel_size: 0.5 # The voxel size for the grid sampling of the new frame (before keypoints extraction)
      sample_voxel_size: 1.5 # The size of a voxel for the selection of `keypoints` by grid sampling

      size_voxel_map: 1.0 # The voxel size of in the voxel map
      min_distance_points: 0.1
      max_num_points_in_voxel: 20 # The maximum number of points per voxel of the map
      max_distance: 100.0 # The threshold of the distance to suppress voxels from the map
      min_number_neighbors: 20 # The minimum number of neighbor points to define a valid neighborhood
      max_number_neighbors: 20

      num_iters_icp: 10 # The number of iterations of the ICP

      debug_print: true
      debug_path: /home/yuchen/ASRL/temp/doppler_odometry/boreas/aeva/spline

      spline:
        T_sr_vec: [-0.835, -0.39, 0.103, 0.0, 0.0, 0.0] # davids result without side slip

        knot_spacing: 0.2

        vp_cov_diag: [1000.0, 0.001, 0.001, 1.0, 1.0, 1000.0]

        rv_loss_func: L2
        rv_cov_inv: 0.1
        rv_loss_threshold: 0.1

        verbose: false
        max_iterations: 1
        num_threads: 10
